// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ChatappConversation struct {
	ID        pgtype.UUID        `json:"id"`
	IsGroup   bool               `json:"is_group"`
	Title     string             `json:"title"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ChatappMessage struct {
	ID             pgtype.UUID        `json:"id"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	SenderID       pgtype.UUID        `json:"sender_id"`
	Content        string             `json:"content"`
	ContentType    string             `json:"content_type"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type ChatappParticipant struct {
	ID             pgtype.UUID        `json:"id"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	JoinedAt       pgtype.Timestamptz `json:"joined_at"`
	LastReadAt     pgtype.Timestamptz `json:"last_read_at"`
}

type ChatappPushSubscription struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Endpoint  string             `json:"endpoint"`
	P256dh    string             `json:"p256dh"`
	Auth      string             `json:"auth"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ChatappRefreshToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ChatappUser struct {
	ID           pgtype.UUID        `json:"id"`
	Username     string             `json:"username"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	DisplayName  string             `json:"display_name"`
	AvatarUrl    string             `json:"avatar_url"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
