// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addParticipant = `-- name: AddParticipant :exec
INSERT INTO chatapp.participants (conversation_id, user_id)
VALUES ($1, $2)
ON CONFLICT (conversation_id, user_id) DO NOTHING
`

type AddParticipantParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

func (q *Queries) AddParticipant(ctx context.Context, arg AddParticipantParams) error {
	_, err := q.db.Exec(ctx, addParticipant, arg.ConversationID, arg.UserID)
	return err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO chatapp.conversations (is_group, title)
VALUES ($1, $2)
RETURNING id, is_group, title, created_at, updated_at
`

type CreateConversationParams struct {
	IsGroup bool   `json:"is_group"`
	Title   string `json:"title"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (ChatappConversation, error) {
	row := q.db.QueryRow(ctx, createConversation, arg.IsGroup, arg.Title)
	var i ChatappConversation
	err := row.Scan(
		&i.ID,
		&i.IsGroup,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO chatapp.messages (conversation_id, sender_id, content, content_type)
VALUES ($1, $2, $3, $4)
RETURNING id, conversation_id, sender_id, content, content_type, created_at
`

type CreateMessageParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	SenderID       pgtype.UUID `json:"sender_id"`
	Content        string      `json:"content"`
	ContentType    string      `json:"content_type"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (ChatappMessage, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ConversationID,
		arg.SenderID,
		arg.Content,
		arg.ContentType,
	)
	var i ChatappMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Content,
		&i.ContentType,
		&i.CreatedAt,
	)
	return i, err
}

const createPushSubscription = `-- name: CreatePushSubscription :exec
INSERT INTO chatapp.push_subscriptions (user_id, endpoint, p256dh, auth)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, endpoint) DO UPDATE
SET p256dh = EXCLUDED.p256dh, auth = EXCLUDED.auth
`

type CreatePushSubscriptionParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Endpoint string      `json:"endpoint"`
	P256dh   string      `json:"p256dh"`
	Auth     string      `json:"auth"`
}

func (q *Queries) CreatePushSubscription(ctx context.Context, arg CreatePushSubscriptionParams) error {
	_, err := q.db.Exec(ctx, createPushSubscription,
		arg.UserID,
		arg.Endpoint,
		arg.P256dh,
		arg.Auth,
	)
	return err
}

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO chatapp.refresh_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
`

type CreateRefreshTokenParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO chatapp.users (username, email, password_hash, display_name)
VALUES ($1, $2, $3, $4)
RETURNING id, username, email, password_hash, display_name, avatar_url, created_at, updated_at
`

type CreateUserParams struct {
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	DisplayName  string `json:"display_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (ChatappUser, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
	)
	var i ChatappUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePushSubscription = `-- name: DeletePushSubscription :exec
DELETE FROM chatapp.push_subscriptions
WHERE user_id = $1 AND endpoint = $2
`

type DeletePushSubscriptionParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Endpoint string      `json:"endpoint"`
}

func (q *Queries) DeletePushSubscription(ctx context.Context, arg DeletePushSubscriptionParams) error {
	_, err := q.db.Exec(ctx, deletePushSubscription, arg.UserID, arg.Endpoint)
	return err
}

const deletePushSubscriptionByEndpoint = `-- name: DeletePushSubscriptionByEndpoint :exec
DELETE FROM chatapp.push_subscriptions
WHERE endpoint = $1
`

func (q *Queries) DeletePushSubscriptionByEndpoint(ctx context.Context, endpoint string) error {
	_, err := q.db.Exec(ctx, deletePushSubscriptionByEndpoint, endpoint)
	return err
}

const deleteRefreshTokenByHash = `-- name: DeleteRefreshTokenByHash :exec
DELETE FROM chatapp.refresh_tokens WHERE token_hash = $1
`

func (q *Queries) DeleteRefreshTokenByHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteRefreshTokenByHash, tokenHash)
	return err
}

const deleteRefreshTokensByUser = `-- name: DeleteRefreshTokensByUser :exec
DELETE FROM chatapp.refresh_tokens WHERE user_id = $1
`

func (q *Queries) DeleteRefreshTokensByUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRefreshTokensByUser, userID)
	return err
}

const findDirectConversation = `-- name: FindDirectConversation :one
SELECT c.id, c.is_group, c.title, c.created_at, c.updated_at
FROM chatapp.conversations c
JOIN chatapp.participants p1 ON p1.conversation_id = c.id
JOIN chatapp.participants p2 ON p2.conversation_id = c.id
WHERE p1.user_id = $1
  AND p2.user_id = $2
  AND c.is_group = false
LIMIT 1
`

type FindDirectConversationParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	UserID_2 pgtype.UUID `json:"user_id_2"`
}

func (q *Queries) FindDirectConversation(ctx context.Context, arg FindDirectConversationParams) (ChatappConversation, error) {
	row := q.db.QueryRow(ctx, findDirectConversation, arg.UserID, arg.UserID_2)
	var i ChatappConversation
	err := row.Scan(
		&i.ID,
		&i.IsGroup,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversationByID = `-- name: GetConversationByID :one
SELECT id, is_group, title, created_at, updated_at
FROM chatapp.conversations WHERE id = $1
`

func (q *Queries) GetConversationByID(ctx context.Context, id pgtype.UUID) (ChatappConversation, error) {
	row := q.db.QueryRow(ctx, getConversationByID, id)
	var i ChatappConversation
	err := row.Scan(
		&i.ID,
		&i.IsGroup,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLastReadAt = `-- name: GetLastReadAt :one
SELECT last_read_at FROM chatapp.participants
WHERE conversation_id = $1 AND user_id = $2
`

type GetLastReadAtParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetLastReadAt(ctx context.Context, arg GetLastReadAtParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getLastReadAt, arg.ConversationID, arg.UserID)
	var last_read_at pgtype.Timestamptz
	err := row.Scan(&last_read_at)
	return last_read_at, err
}

const getParticipants = `-- name: GetParticipants :many
SELECT user_id FROM chatapp.participants WHERE conversation_id = $1
`

func (q *Queries) GetParticipants(ctx context.Context, conversationID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getParticipants, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var user_id pgtype.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPushSubscriptionsByUser = `-- name: GetPushSubscriptionsByUser :many
SELECT id, user_id, endpoint, p256dh, auth, created_at
FROM chatapp.push_subscriptions
WHERE user_id = $1
`

func (q *Queries) GetPushSubscriptionsByUser(ctx context.Context, userID pgtype.UUID) ([]ChatappPushSubscription, error) {
	rows, err := q.db.Query(ctx, getPushSubscriptionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatappPushSubscription
	for rows.Next() {
		var i ChatappPushSubscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Endpoint,
			&i.P256dh,
			&i.Auth,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, token_hash, expires_at, created_at
FROM chatapp.refresh_tokens WHERE token_hash = $1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (ChatappRefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i ChatappRefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, display_name, avatar_url, created_at, updated_at
FROM chatapp.users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (ChatappUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i ChatappUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hash, display_name, avatar_url, created_at, updated_at
FROM chatapp.users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (ChatappUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i ChatappUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password_hash, display_name, avatar_url, created_at, updated_at
FROM chatapp.users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (ChatappUser, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i ChatappUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isParticipant = `-- name: IsParticipant :one
SELECT EXISTS(
    SELECT 1 FROM chatapp.participants WHERE conversation_id = $1 AND user_id = $2
) AS is_participant
`

type IsParticipantParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

func (q *Queries) IsParticipant(ctx context.Context, arg IsParticipantParams) (bool, error) {
	row := q.db.QueryRow(ctx, isParticipant, arg.ConversationID, arg.UserID)
	var is_participant bool
	err := row.Scan(&is_participant)
	return is_participant, err
}

const listConversationsByUser = `-- name: ListConversationsByUser :many
SELECT
    c.id, c.is_group, c.title, c.created_at, c.updated_at,
    u.id AS other_user_id, u.username AS other_username,
    u.display_name AS other_display_name, u.avatar_url AS other_avatar_url,
    m.id AS last_msg_id, COALESCE(m.content, '') AS last_msg_content,
    m.sender_id AS last_msg_sender_id, m.created_at AS last_msg_created_at,
    COALESCE((
        SELECT COUNT(*) FROM chatapp.messages msg
        WHERE msg.conversation_id = c.id AND msg.created_at > p.last_read_at
    ), 0)::int AS unread_count
FROM chatapp.conversations c
JOIN chatapp.participants p ON p.conversation_id = c.id AND p.user_id = $1
LEFT JOIN chatapp.participants p2 ON p2.conversation_id = c.id AND p2.user_id != $1
LEFT JOIN chatapp.users u ON u.id = p2.user_id
LEFT JOIN LATERAL (
    SELECT id, content, sender_id, created_at
    FROM chatapp.messages
    WHERE conversation_id = c.id
    ORDER BY created_at DESC
    LIMIT 1
) m ON true
ORDER BY COALESCE(m.created_at, c.created_at) DESC
`

type ListConversationsByUserRow struct {
	ID               pgtype.UUID        `json:"id"`
	IsGroup          bool               `json:"is_group"`
	Title            string             `json:"title"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	OtherUserID      pgtype.UUID        `json:"other_user_id"`
	OtherUsername    pgtype.Text        `json:"other_username"`
	OtherDisplayName pgtype.Text        `json:"other_display_name"`
	OtherAvatarUrl   pgtype.Text        `json:"other_avatar_url"`
	LastMsgID        pgtype.UUID        `json:"last_msg_id"`
	LastMsgContent   string             `json:"last_msg_content"`
	LastMsgSenderID  pgtype.UUID        `json:"last_msg_sender_id"`
	LastMsgCreatedAt pgtype.Timestamptz `json:"last_msg_created_at"`
	UnreadCount      int32              `json:"unread_count"`
}

func (q *Queries) ListConversationsByUser(ctx context.Context, userID pgtype.UUID) ([]ListConversationsByUserRow, error) {
	rows, err := q.db.Query(ctx, listConversationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConversationsByUserRow
	for rows.Next() {
		var i ListConversationsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.IsGroup,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OtherUserID,
			&i.OtherUsername,
			&i.OtherDisplayName,
			&i.OtherAvatarUrl,
			&i.LastMsgID,
			&i.LastMsgContent,
			&i.LastMsgSenderID,
			&i.LastMsgCreatedAt,
			&i.UnreadCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByConversation = `-- name: ListMessagesByConversation :many
SELECT id, conversation_id, sender_id, content, content_type, created_at
FROM chatapp.messages
WHERE conversation_id = $1 AND created_at < $2
ORDER BY created_at DESC
LIMIT $3
`

type ListMessagesByConversationParams struct {
	ConversationID pgtype.UUID        `json:"conversation_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Limit          int32              `json:"limit"`
}

func (q *Queries) ListMessagesByConversation(ctx context.Context, arg ListMessagesByConversationParams) ([]ChatappMessage, error) {
	rows, err := q.db.Query(ctx, listMessagesByConversation, arg.ConversationID, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatappMessage
	for rows.Next() {
		var i ChatappMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.Content,
			&i.ContentType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markConversationRead = `-- name: MarkConversationRead :exec
UPDATE chatapp.participants
SET last_read_at = now()
WHERE conversation_id = $1 AND user_id = $2
`

type MarkConversationReadParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

func (q *Queries) MarkConversationRead(ctx context.Context, arg MarkConversationReadParams) error {
	_, err := q.db.Exec(ctx, markConversationRead, arg.ConversationID, arg.UserID)
	return err
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, username, email, display_name, avatar_url, created_at, updated_at
FROM chatapp.users
WHERE username ILIKE '%' || $1 || '%' OR display_name ILIKE '%' || $1 || '%'
LIMIT $2
`

type SearchUsersParams struct {
	Column1 pgtype.Text `json:"column_1"`
	Limit   int32       `json:"limit"`
}

type SearchUsersRow struct {
	ID          pgtype.UUID        `json:"id"`
	Username    string             `json:"username"`
	Email       string             `json:"email"`
	DisplayName string             `json:"display_name"`
	AvatarUrl   string             `json:"avatar_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error) {
	rows, err := q.db.Query(ctx, searchUsers, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchUsersRow
	for rows.Next() {
		var i SearchUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE chatapp.users
SET display_name = COALESCE(NULLIF($1::text, ''), display_name),
    avatar_url   = COALESCE(NULLIF($2::text, ''), avatar_url),
    updated_at   = now()
WHERE id = $3
RETURNING id, username, email, password_hash, display_name, avatar_url, created_at, updated_at
`

type UpdateUserParams struct {
	DisplayName string      `json:"display_name"`
	AvatarUrl   string      `json:"avatar_url"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (ChatappUser, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.DisplayName, arg.AvatarUrl, arg.ID)
	var i ChatappUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
